/* ═══════════════════════════════════════════════════════════
   LANG.JS -- EN / ES translation engine
   Usage: App.Lang.t('key')  returns string in current lang.
   Toggle: App.Lang.setLang('es') / App.Lang.setLang('en')
═══════════════════════════════════════════════════════════ */

(function(App) {
  'use strict';

  var STRINGS = {
    en: {
      // Navigation
      'nav.dashboard':   'Dashboard',
      'nav.accounts':    'Accounts',
      'nav.transfers':   'Transfers',
      'nav.planner':     'Planner',
      'nav.invest':      'Invest',
      'nav.settings':    'Settings',
      'nav.tracker':     'Tracker',
      'nav.entry':       'Entry',

      // Common actions / labels
      'common.save':       'Save',
      'common.add':        'Add',
      'common.edit':       'Edit',
      'common.delete':     'Delete',
      'common.cancel':     'Cancel',
      'common.close':      'Close',
      'common.apply':      'Apply',
      'common.lock':       'Lock',
      'common.unlock':     'Unlock',
      'common.amount':     'Amount ($)',
      'common.name':       'Name',
      'common.date':       'Date',
      'common.note':       'Note',
      'common.notes':      'Notes',
      'common.total':      'Total',
      'common.balance':    'Balance',
      'common.goal':       'Goal',
      'common.annual':     'Annual',
      'common.monthly':    'Monthly',
      'common.remaining':  'Remaining',
      'common.allocated':  'Allocated',
      'common.surplus':    'Surplus',
      'common.deficit':    'Deficit',
      'common.fixed':      'fixed',
      'common.custom':     'custom',
      'common.perCheck':   '/check',
      'common.perYear':    '/year',
      'common.onTrack':    'On track',
      'common.yes':        'Yes',
      'common.no':         'No',
      'common.of':         'of',
      'common.paychecks':  'paychecks',
      'common.weeks':      'weeks',
      'common.optional':   '(optional)',
      'common.overridden': 'overridden',

      // Dashboard
      'dash.netWorth':        'Total Net Worth',
      'dash.safeToSpend':     'Safe to Spend Today',
      'dash.cashOnHand':      'Cash on hand',
      'dash.upcomingBills':   'Upcoming fixed bills',
      'dash.allocatedVaults': 'Allocated to vaults',
      'dash.discretionary':   'Discretionary',
      'dash.thisMonth':       'This Month',
      'dash.income':          'Income',
      'dash.spent':           'Spent',
      'dash.netSavings':      'Net Savings',
      'dash.vsLastMonth':     'vs Last Month',
      'dash.savingsGoals':    'Savings Goals',
      'dash.upcomingChanges': 'Upcoming Changes',
      'dash.weeklySpend':     'Weekly Spend Tracker',
      'dash.weeklyPace':      'Budget pace vs. actual MTD spend',
      'dash.liquid':          'Liquid (checking)',
      'dash.available':       'Available (savings)',
      'dash.invested':        'Invested',
      'dash.lessDebt':        'Less: card debt',
      'dash.cardAlerts':      'Credit Card Alerts',
      'dash.mtdSpent':        'MTD Spent',
      'dash.leftThisMonth':   'Left this month',
      'dash.reminders':       'Reminders & Alerts',
      'dash.reminderDue':     'Due',
      'dash.reminderOverdue': 'Overdue',
      'dash.noReminders':     'No upcoming reminders.',
      'dash.charts':          'Charts',
      'dash.nwHistory':       'Net Worth -- 12 Months',
      'dash.spendingBycat':   'Monthly Spending by Category',
      'dash.investGrowth':    'Investment Growth',
      'dash.paycheckPerf':    'Paycheck Performance',

      // Accounts
      'acct.vaults':          'Vaults',
      'acct.bankAccounts':    'Bank Accounts',
      'acct.creditCards':     'Credit Cards',
      'acct.totalVaults':     'Total Vaults',
      'acct.totalCash':       'total cash',
      'acct.totalDebt':       'Total Debt',
      'acct.safetyNet':       'Safety Net',
      'acct.safetyNetDesc':   'months of expenses covered',
      'acct.addVault':        '+ Add Vault',
      'acct.addBank':         '+ Add Bank Account',
      'acct.addCard':         '+ Add Credit Card',
      'acct.limit':           'Limit',
      'acct.used':            'used',
      'acct.liquid':          'Immediate',
      'acct.short':           'Short-term',
      'acct.locked':          'Locked',
      'acct.isTransfer':      'Transfer account',
      'acct.vaultName':       'Vault Name',
      'acct.linkedCategory':  'Linked Category',
      'acct.liquidityTier':   'Liquidity Tier',
      'acct.editVault':       'Edit Vault',
      'acct.editBank':        'Edit Bank Account',
      'acct.editCard':        'Edit Credit Card',
      'acct.saveVault':       'Save Vault',
      'acct.saveBank':        'Save Bank Account',
      'acct.saveCard':        'Save Credit Card',
      'acct.cardName':        'Card Name',
      'acct.cardLimit':       'Credit Limit',
      'acct.accounts':        'accounts',

      // Transfers
      'trans.paycheckArrived': 'Paycheck Arrived',
      'trans.payCards':        'Pay Cards',
      'trans.moveMoney':       'Move Money',
      'trans.fundVault':       'Fund Vault',
      'trans.withdraw':        'Withdraw from Vault',
      'trans.execute':         'Execute',
      'trans.available':       'Available',
      'trans.netPay':          'Net Pay',
      'trans.payAmount':       'Pay Amount',
      'trans.from':            'From',
      'trans.to':              'To',
      'trans.allCards':        'Pay All Cards',
      'trans.selectCard':      'Select card',
      'trans.selectVault':     'Select vault',
      'trans.selectBank':      'Select bank account',
      'trans.partial':         'Partial',
      'trans.full':            'Full',

      // Planner
      'plan.paycheckOf':    'of',
      'plan.prevMonth':     'Previous Month',
      'plan.nextMonth':     'Next Month',
      'plan.paycheckAmt':   'Paycheck Amount ($)',
      'plan.category':      'Category',
      'plan.lockAmount':    'Lock',
      'plan.savePaycheck':  'Save Paycheck',
      'plan.customItem':    'Custom Item',
      'plan.customName':    'Name',
      'plan.customAmt':     'Amount',
      'plan.weeklyBudget':  'Weekly Budget Settings',
      'plan.weeklyDesc':    'Food & Gas calculated from day counts',
      'plan.saveWeekly':    'Save Weekly Budgets',
      'plan.perWeek':       '$/wk',
      'plan.upcoming':      'Upcoming Expenses',
      'plan.upcomingDesc':  'planned',
      'plan.addUpcoming':   '+ Add Expense',
      'plan.monthYYYYMM':   'Month (YYYY-MM)',
      'plan.payee':         'Payee / Description',
      'plan.monthTotals':   'Month Totals',
      'plan.notes':         'Notes / Reminders',
      'plan.notesHint':     'e.g. Rent due, car payment, upcoming expense...',
      'plan.reminders':     'Reminders',
      'plan.reminderText':  'Note / Description',
      'plan.reminderDate':  'Due Date',
      'plan.reminderAmt':   'Amount (optional)',
      'plan.addReminder':   '+ Add Reminder',
      'plan.noReminders':   'No reminders yet.',
      'plan.saveReminder':  'Save Reminder',

      // Tracker
      'track.period':        '#',
      'track.payDate':       'Pay Date',
      'track.saved':         'Saved',
      'track.expected':      'Expected',
      'track.variance':      '+/-',
      'track.rank':          'Rank',
      'track.ytdSaved':      'YTD Saved',
      'track.expectedPace':  'Expected Pace',
      'track.aheadOfPace':   'Ahead of Pace',
      'track.behindPace':    'Behind Pace',
      'track.enterHint':     'Enter the amount saved each paycheck -- Tab or Enter to save, ranked automatically.',
      'track.ytdByCategory': 'YTD by Category',
      'track.annualGoal':    'Annual Goal',
      'track.ytdSpent':      'YTD Spent',
      'track.pctOfYear':     '% of Year',
      'track.savingsPlan':   'Savings Plan -- Year-End Projection',
      'track.periodsComplete': 'periods complete',
      'track.remaining':     'remaining',
      'track.projectedTotal':'Projected Total',
      'track.annualGoal2':   'Annual Goal',
      'track.shortfall':     'Shortfall',
      'track.surplusLbl':    'Surplus',
      'track.perCheck':      'Per Check',
      'track.projected':     'Projected',
      'track.challenge':     'Savings Challenge',
      'track.currentAvg':    'Your current avg',
      'track.neededGoals':   'needed for goals',
      'track.matchGoals':    'Match Goals',
      'track.stretch10':     '+10% Stretch',
      'track.ambitious20':   '+20% Ambitious',
      'track.covered':       "you're covered",
      'track.base':          'Base /check',
      'track.plus10':        '+10% /check',
      'track.plus20':        '+20% /check',
      'track.paychecksElapsed': 'paychecks elapsed',
      'track.avg':           'avg',

      // Investments
      'invest.holdings':     'Holdings',
      'invest.ticker':       'Ticker',
      'invest.shares':       'Shares',
      'invest.price':        'Price',
      'invest.value':        'Value',
      'invest.addHolding':   '+ Add Holding',
      'invest.contributions':'Contributions',
      'invest.ytdContrib':   'YTD Contributions',
      'invest.goal':         'Annual Goal',
      'invest.accounts':     'Investment Accounts',
      'invest.totalValue':   'Total Value',
      'invest.rothIra':      'Roth IRA',
      'invest.account':      'Account',

      // Settings / Setup
      'set.account':         'Account',
      'set.theme':           'Theme',
      'set.language':        'Language',
      'set.dark':            'Dark (Neon)',
      'set.light':           'Light',
      'set.system':          'System',
      'set.english':         'English',
      'set.spanish':         'Espanol',
      'set.exportData':      'Export Data',
      'set.importData':      'Import Data',
      'set.clearData':       'Clear All Data',
      'set.income':          'Income',
      'set.categories':      'Savings Categories',
      'set.fixedExpenses':   'Fixed Monthly Expenses',
      'set.frequency':       'Pay Frequency',
      'set.firstPayday':     'First Payday of Year',
      'set.paycheckAmount':  'Default Paycheck Amount',
      'set.addCategory':     '+ Add Category',
      'set.addExpense':      '+ Add Fixed Expense',
      'set.categoryName':    'Category Name',
      'set.annualGoal':      'Annual Goal ($)',
      'set.weeklyBudget':    'Weekly Budget ($)',
      'set.weeklyDay':       'Shopping Day',
      'set.sunday':          'Sunday',
      'set.saturday':        'Saturday',
      'set.targetDate':      'Goal Target Date',
      'set.targetAmount':    'Target Amount ($)',
      'set.saveCategory':    'Save Category',
      'set.saveExpense':     'Save Expense',
      'set.partnerIncome':   'Partner Income',
      'set.partnerEnabled':  'Enable partner income',
    },

    es: {
      // Navegacion
      'nav.dashboard':   'Tablero',
      'nav.accounts':    'Cuentas',
      'nav.transfers':   'Transferencias',
      'nav.planner':     'Planificador',
      'nav.invest':      'Invertir',
      'nav.settings':    'Ajustes',
      'nav.tracker':     'Registro',
      'nav.entry':       'Entrada',

      // Comun
      'common.save':       'Guardar',
      'common.add':        'Agregar',
      'common.edit':       'Editar',
      'common.delete':     'Eliminar',
      'common.cancel':     'Cancelar',
      'common.close':      'Cerrar',
      'common.apply':      'Aplicar',
      'common.lock':       'Bloquear',
      'common.unlock':     'Desbloquear',
      'common.amount':     'Cantidad ($)',
      'common.name':       'Nombre',
      'common.date':       'Fecha',
      'common.note':       'Nota',
      'common.notes':      'Notas',
      'common.total':      'Total',
      'common.balance':    'Saldo',
      'common.goal':       'Meta',
      'common.annual':     'Anual',
      'common.monthly':    'Mensual',
      'common.remaining':  'Restante',
      'common.allocated':  'Asignado',
      'common.surplus':    'Sobrante',
      'common.deficit':    'Deficit',
      'common.fixed':      'fijo',
      'common.custom':     'personalizado',
      'common.perCheck':   '/cheque',
      'common.perYear':    '/ano',
      'common.onTrack':    'Al dia',
      'common.yes':        'Si',
      'common.no':         'No',
      'common.of':         'de',
      'common.paychecks':  'cheques',
      'common.weeks':      'semanas',
      'common.optional':   '(opcional)',
      'common.overridden': 'modificado',

      // Tablero
      'dash.netWorth':        'Patrimonio Neto',
      'dash.safeToSpend':     'Disponible para Gastar',
      'dash.cashOnHand':      'Efectivo disponible',
      'dash.upcomingBills':   'Facturas proximas',
      'dash.allocatedVaults': 'Asignado a fondos',
      'dash.discretionary':   'Discrecional',
      'dash.thisMonth':       'Este Mes',
      'dash.income':          'Ingresos',
      'dash.spent':           'Gastado',
      'dash.netSavings':      'Ahorro Neto',
      'dash.vsLastMonth':     'vs Mes Anterior',
      'dash.savingsGoals':    'Metas de Ahorro',
      'dash.upcomingChanges': 'Cambios Proximos',
      'dash.weeklySpend':     'Control Semanal',
      'dash.weeklyPace':      'Presupuesto semanal vs. gasto real del mes',
      'dash.liquid':          'Liquido (corriente)',
      'dash.available':       'Disponible (ahorros)',
      'dash.invested':        'Invertido',
      'dash.lessDebt':        'Menos: deuda tarjetas',
      'dash.cardAlerts':      'Alertas de Tarjetas',
      'dash.mtdSpent':        'Gastado (mes)',
      'dash.leftThisMonth':   'Disponible (mes)',
      'dash.reminders':       'Recordatorios y Alertas',
      'dash.reminderDue':     'Vence',
      'dash.reminderOverdue': 'Vencido',
      'dash.noReminders':     'Sin recordatorios proximos.',
      'dash.charts':          'Graficas',
      'dash.nwHistory':       'Patrimonio -- 12 Meses',
      'dash.spendingBycat':   'Gasto Mensual por Categoria',
      'dash.investGrowth':    'Crecimiento de Inversiones',
      'dash.paycheckPerf':    'Rendimiento por Cheque',

      // Cuentas
      'acct.vaults':          'Fondos',
      'acct.bankAccounts':    'Cuentas Bancarias',
      'acct.creditCards':     'Tarjetas de Credito',
      'acct.totalVaults':     'Total Fondos',
      'acct.totalCash':       'efectivo total',
      'acct.totalDebt':       'Deuda Total',
      'acct.safetyNet':       'Fondo de Emergencia',
      'acct.safetyNetDesc':   'meses de gastos cubiertos',
      'acct.addVault':        '+ Agregar Fondo',
      'acct.addBank':         '+ Agregar Cuenta Bancaria',
      'acct.addCard':         '+ Agregar Tarjeta',
      'acct.limit':           'Limite',
      'acct.used':            'usado',
      'acct.liquid':          'Inmediato',
      'acct.short':           'Corto plazo',
      'acct.locked':          'Bloqueado',
      'acct.isTransfer':      'Cuenta de transferencia',
      'acct.vaultName':       'Nombre del Fondo',
      'acct.linkedCategory':  'Categoria vinculada',
      'acct.liquidityTier':   'Nivel de Liquidez',
      'acct.editVault':       'Editar Fondo',
      'acct.editBank':        'Editar Cuenta Bancaria',
      'acct.editCard':        'Editar Tarjeta',
      'acct.saveVault':       'Guardar Fondo',
      'acct.saveBank':        'Guardar Cuenta Bancaria',
      'acct.saveCard':        'Guardar Tarjeta',
      'acct.cardName':        'Nombre de la Tarjeta',
      'acct.cardLimit':       'Limite de Credito',
      'acct.accounts':        'cuentas',

      // Transferencias
      'trans.paycheckArrived': 'Llego el Cheque',
      'trans.payCards':        'Pagar Tarjetas',
      'trans.moveMoney':       'Mover Dinero',
      'trans.fundVault':       'Depositar en Fondo',
      'trans.withdraw':        'Retirar del Fondo',
      'trans.execute':         'Ejecutar',
      'trans.available':       'Disponible',
      'trans.netPay':          'Pago Neto',
      'trans.payAmount':       'Monto a Pagar',
      'trans.from':            'De',
      'trans.to':              'A',
      'trans.allCards':        'Pagar Todas las Tarjetas',
      'trans.selectCard':      'Seleccionar tarjeta',
      'trans.selectVault':     'Seleccionar fondo',
      'trans.selectBank':      'Seleccionar cuenta bancaria',
      'trans.partial':         'Parcial',
      'trans.full':            'Completo',

      // Planificador
      'plan.paycheckOf':    'de',
      'plan.prevMonth':     'Mes Anterior',
      'plan.nextMonth':     'Mes Siguiente',
      'plan.paycheckAmt':   'Monto del Cheque ($)',
      'plan.category':      'Categoria',
      'plan.lockAmount':    'Fijar',
      'plan.savePaycheck':  'Guardar Cheque',
      'plan.customItem':    'Elemento Personalizado',
      'plan.customName':    'Nombre',
      'plan.customAmt':     'Cantidad',
      'plan.weeklyBudget':  'Presupuesto Semanal',
      'plan.weeklyDesc':    'Comida y Gasolina calculados por dias del mes',
      'plan.saveWeekly':    'Guardar Presupuesto Semanal',
      'plan.perWeek':       '$/sem',
      'plan.upcoming':      'Gastos Proximos',
      'plan.upcomingDesc':  'planificados',
      'plan.addUpcoming':   '+ Agregar Gasto',
      'plan.monthYYYYMM':   'Mes (AAAA-MM)',
      'plan.payee':         'Beneficiario / Descripcion',
      'plan.monthTotals':   'Totales del Mes',
      'plan.notes':         'Notas / Recordatorios',
      'plan.notesHint':     'Ej. Renta vence, pago de auto, gasto proximo...',
      'plan.reminders':     'Recordatorios',
      'plan.reminderText':  'Nota / Descripcion',
      'plan.reminderDate':  'Fecha de Vencimiento',
      'plan.reminderAmt':   'Cantidad (opcional)',
      'plan.addReminder':   '+ Agregar Recordatorio',
      'plan.noReminders':   'Sin recordatorios aun.',
      'plan.saveReminder':  'Guardar Recordatorio',

      // Registro
      'track.period':        '#',
      'track.payDate':       'Fecha de Pago',
      'track.saved':         'Ahorrado',
      'track.expected':      'Esperado',
      'track.variance':      '+/-',
      'track.rank':          'Posicion',
      'track.ytdSaved':      'Ahorrado (YTD)',
      'track.expectedPace':  'Ritmo Esperado',
      'track.aheadOfPace':   'Adelante',
      'track.behindPace':    'Atrasado',
      'track.enterHint':     'Ingresa el monto ahorrado por cheque -- Tab o Enter para guardar.',
      'track.ytdByCategory': 'YTD por Categoria',
      'track.annualGoal':    'Meta Anual',
      'track.ytdSpent':      'Gastado (YTD)',
      'track.pctOfYear':     '% del Ano',
      'track.savingsPlan':   'Plan de Ahorro -- Proyeccion Anual',
      'track.periodsComplete': 'periodos completos',
      'track.remaining':     'restantes',
      'track.projectedTotal':'Total Proyectado',
      'track.annualGoal2':   'Meta Anual',
      'track.shortfall':     'Deficit',
      'track.surplusLbl':    'Sobrante',
      'track.perCheck':      'Por Cheque',
      'track.projected':     'Proyectado',
      'track.challenge':     'Desafio de Ahorro',
      'track.currentAvg':    'Tu promedio actual',
      'track.neededGoals':   'necesario para metas',
      'track.matchGoals':    'Cumplir Metas',
      'track.stretch10':     '+10% Esfuerzo',
      'track.ambitious20':   '+20% Ambicioso',
      'track.covered':       'ya lo alcanzas',
      'track.base':          'Base /cheque',
      'track.plus10':        '+10% /cheque',
      'track.plus20':        '+20% /cheque',
      'track.paychecksElapsed': 'cheques transcurridos',
      'track.avg':           'prom',

      // Inversiones
      'invest.holdings':     'Posiciones',
      'invest.ticker':       'Simbolo',
      'invest.shares':       'Acciones',
      'invest.price':        'Precio',
      'invest.value':        'Valor',
      'invest.addHolding':   '+ Agregar Posicion',
      'invest.contributions':'Contribuciones',
      'invest.ytdContrib':   'Contribuciones YTD',
      'invest.goal':         'Meta Anual',
      'invest.accounts':     'Cuentas de Inversion',
      'invest.totalValue':   'Valor Total',
      'invest.rothIra':      'Roth IRA',
      'invest.account':      'Cuenta',

      // Ajustes
      'set.account':         'Cuenta',
      'set.theme':           'Tema',
      'set.language':        'Idioma',
      'set.dark':            'Oscuro (Neon)',
      'set.light':           'Claro',
      'set.system':          'Sistema',
      'set.english':         'English',
      'set.spanish':         'Espanol',
      'set.exportData':      'Exportar Datos',
      'set.importData':      'Importar Datos',
      'set.clearData':       'Borrar Todos los Datos',
      'set.income':          'Ingresos',
      'set.categories':      'Categorias de Ahorro',
      'set.fixedExpenses':   'Gastos Fijos Mensuales',
      'set.frequency':       'Frecuencia de Pago',
      'set.firstPayday':     'Primer Dia de Pago del Ano',
      'set.paycheckAmount':  'Monto Predeterminado del Cheque',
      'set.addCategory':     '+ Agregar Categoria',
      'set.addExpense':      '+ Agregar Gasto Fijo',
      'set.categoryName':    'Nombre de la Categoria',
      'set.annualGoal':      'Meta Anual ($)',
      'set.weeklyBudget':    'Presupuesto Semanal ($)',
      'set.weeklyDay':       'Dia de Compras',
      'set.sunday':          'Domingo',
      'set.saturday':        'Sabado',
      'set.targetDate':      'Fecha Meta',
      'set.targetAmount':    'Cantidad Meta ($)',
      'set.saveCategory':    'Guardar Categoria',
      'set.saveExpense':     'Guardar Gasto',
      'set.partnerIncome':   'Ingresos del Conyuge',
      'set.partnerEnabled':  'Activar ingresos del conyuge',
    }
  };

  var _lang = 'en';

  function t(key) {
    var dict = STRINGS[_lang] || STRINGS['en'];
    return dict[key] !== undefined ? dict[key] : (STRINGS['en'][key] || key);
  }

  function setLang(lang) {
    if (lang !== 'en' && lang !== 'es') return;
    _lang = lang;
    // Persist
    try {
      var state = App.Storage ? App.Storage.loadState() : null;
      if (state) {
        if (!state.settings) state.settings = {};
        state.settings.lang = lang;
        App.Storage.saveState(state);
      }
      localStorage.setItem('financeApp_lang', lang);
    } catch(e) {}
    // Re-render current tab
    if (App.refreshCurrentTab) App.refreshCurrentTab();
    // Update nav labels
    updateNavLabels();
    // Update html lang attribute
    document.documentElement.lang = lang;
  }

  function getLang() { return _lang; }

  function init() {
    // Load saved lang
    try {
      var saved = localStorage.getItem('financeApp_lang');
      if (saved === 'en' || saved === 'es') _lang = saved;
    } catch(e) {}
    updateNavLabels();
    document.documentElement.lang = _lang;
  }

  function updateNavLabels() {
    var map = {
      'dashboard':   'nav.dashboard',
      'accounts':    'nav.accounts',
      'transfers':   'nav.transfers',
      'planner':     'nav.planner',
      'investments': 'nav.invest',
      'settings':    'nav.settings'
    };
    document.querySelectorAll('.tab-btn[data-tab]').forEach(function(btn) {
      var key = map[btn.dataset.tab];
      if (key) {
        var label = btn.querySelector('.tab-label');
        if (label) label.textContent = t(key);
      }
    });
    // Also update the lang toggle button text if it exists
    var toggle = document.getElementById('lang-toggle');
    if (toggle) toggle.textContent = _lang === 'en' ? 'ES' : 'EN';
  }

  App.Lang = { t: t, setLang: setLang, getLang: getLang, init: init };

})(window.App = window.App || {});
