/* ═══════════════════════════════════════════════════════════
   LANG.JS -- EN / ES translation engine
   Usage: App.Lang.t('key')  returns string in current lang.
   Toggle: App.Lang.setLang('es') / App.Lang.setLang('en')
═══════════════════════════════════════════════════════════ */

(function(App) {
  'use strict';

  var STRINGS = {
    en: {
      // Navigation
      'nav.dashboard':   'Dashboard',
      'nav.accounts':    'Accounts',
      'nav.transfers':   'Transfers',
      'nav.planner':     'Planner',
      'nav.invest':      'Invest',
      'nav.settings':    'Settings',
      'nav.tracker':     'Tracker',
      'nav.entry':       'Entry',
      'nav.goals':       'Goals',
      'nav.calendar':    'Calendar',
      'nav.paycheck-tracker': 'Pck Tracker',
      'nav.savings-plan':     'Savings Plan',
      'nav.next-year':        'Next Year',

      // Paycheck Tracker
      'pct.title':       'Paycheck Tracker',
      'pct.addCol':      'Add Column',
      'pct.colName':     'Column name',
      'pct.removeCol':   'Remove column',
      'pct.period':      'Period',
      'pct.total':       'Total',
      'pct.totals':      'Totals',
      'pct.cols':        'Columns',
      'pct.grandTotal':  'Grand Total',
      'pct.pace':        'Pace',

      // Savings Plan
      'splan.week52':         '52-Week Savings Challenge',
      'splan.biweekly26':     '26 Bi-Weekly Savings Challenge',
      'splan.startAt':        'Start at $',
      'splan.week':           'Week',
      'splan.period':         'Period',
      'splan.saveThisWeek':   'Save This Week',
      'splan.saveThisPeriod': 'Save This Period',
      'splan.totalSaved':     'Total Saved',
      'splan.yearEnd':        'Year-End Total',
      'splan.completed':      'completed',
      'splan.saved':          'saved so far',

      // Next Year Planner
      'nyp.title':            'Planner',
      'nyp.resetFromCurrent': 'Reset from Current Year',
      'nyp.paycheckAmt':      'Paycheck Amount ($)',
      'nyp.allocated':        'Allocated',
      'nyp.surplus':          'Surplus',
      'nyp.paychecks':        'Paychecks',
      'nyp.lineItems':        'Line Items — Per Paycheck',
      'nyp.category':         'Category',
      'nyp.perCheck':         '/ Check',
      'nyp.annual':           'Annual',
      'nyp.newLineName':      'New line item name',
      'nyp.nameRequired':     'Name is required',
      'nyp.resetDone':        'Reset from current year categories',
      'nyp.annualSummary':    'Annual Summary',
      'nyp.totalIncome':      'Total Income',
      'nyp.totalAllocated':   'Total Allocated',
      'nyp.totalSurplus':     'Total Surplus',
      'nyp.activate':          'Activate for',
      'nyp.activateConfirm':   'This will update your current year categories with the amounts from this plan.',
      'nyp.activateStep1':     'Updates weeklyBudget on matching categories',
      'nyp.activateStep2':     'Your live Planner will use these new amounts immediately',
      'nyp.activateStep3':     'Advances this planner to',
      'nyp.activateConfirmBtn':'Activate Now',
      'nyp.activateDone':      'Activated! Planner advanced to',

      // Common
      'cancel':  'Cancel',
      'add':     'Add',

      // Common actions / labels
      'common.save':       'Save',
      'common.add':        'Add',
      'common.edit':       'Edit',
      'common.delete':     'Delete',
      'common.cancel':     'Cancel',
      'common.close':      'Close',
      'common.apply':      'Apply',
      'common.lock':       'Lock',
      'common.unlock':     'Unlock',
      'common.amount':     'Amount ($)',
      'common.name':       'Name',
      'common.date':       'Date',
      'common.note':       'Note',
      'common.notes':      'Notes',
      'common.total':      'Total',
      'common.balance':    'Balance',
      'common.goal':       'Goal',
      'common.annual':     'Annual',
      'common.monthly':    'Monthly',
      'common.remaining':  'Remaining',
      'common.allocated':  'Allocated',
      'common.surplus':    'Surplus',
      'common.deficit':    'Deficit',
      'common.fixed':      'fixed',
      'common.custom':     'custom',
      'common.perCheck':   '/check',
      'common.perYear':    '/year',
      'common.onTrack':    'On track',
      'common.yes':        'Yes',
      'common.no':         'No',
      'common.of':         'of',
      'common.paychecks':  'paychecks',
      'common.weeks':      'weeks',
      'common.optional':   '(optional)',
      'common.overridden': 'overridden',

      // Dashboard
      'dash.netWorth':        'Total Net Worth',
      'dash.safeToSpend':     'Safe to Spend Today',
      'dash.cashOnHand':      'Cash on hand',
      'dash.upcomingBills':   'Upcoming fixed bills',
      'dash.allocatedVaults': 'Allocated to vaults',
      'dash.discretionary':   'Discretionary',
      'dash.thisMonth':       'This Month',
      'dash.income':          'Income',
      'dash.spent':           'Spent',
      'dash.netSavings':      'Net Savings',
      'dash.vsLastMonth':     'vs Last Month',
      'dash.savingsGoals':    'Savings Goals',
      'dash.upcomingChanges': 'Upcoming Changes',
      'dash.weeklySpend':     'Weekly Spend Tracker',
      'dash.weeklyPace':      'Budget pace vs. actual MTD spend',
      'dash.liquid':          'Liquid (checking)',
      'dash.available':       'Available (savings)',
      'dash.invested':        'Invested',
      'dash.lessDebt':        'Less: card debt',
      'dash.cardAlerts':      'Credit Card Alerts',
      'dash.mtdSpent':        'MTD Spent',
      'dash.leftThisMonth':   'Left this month',
      'dash.reminders':       'Reminders & Alerts',
      'dash.reminderDue':     'Due',
      'dash.reminderOverdue': 'Overdue',
      'dash.noReminders':     'No upcoming reminders.',
      'dash.charts':          'Charts',
      'dash.nwHistory':       'Net Worth -- 12 Months',
      'dash.spendingBycat':   'Monthly Spending by Category',
      'dash.investGrowth':    'Investment Growth',
      'dash.paycheckPerf':    'Paycheck Performance',

      // Accounts
      'acct.vaults':          'Vaults',
      'acct.bankAccounts':    'Bank Accounts',
      'acct.creditCards':     'Credit Cards',
      'acct.totalVaults':     'Total Vaults',
      'acct.totalCash':       'total cash',
      'acct.totalDebt':       'Total Debt',
      'acct.safetyNet':       'Safety Net',
      'acct.safetyNetDesc':   'months of expenses covered',
      'acct.addVault':        '+ Add Vault',
      'acct.addBank':         '+ Add Bank Account',
      'acct.addCard':         '+ Add Credit Card',
      'acct.limit':           'Limit',
      'acct.used':            'used',
      'acct.liquid':          'Immediate',
      'acct.short':           'Short-term',
      'acct.locked':          'Locked',
      'acct.isTransfer':      'Transfer account',
      'acct.vaultName':       'Vault Name',
      'acct.linkedCategory':  'Linked Category',
      'acct.liquidityTier':   'Liquidity Tier',
      'acct.editVault':       'Edit Vault',
      'acct.editBank':        'Edit Bank Account',
      'acct.editCard':        'Edit Credit Card',
      'acct.saveVault':       'Save Vault',
      'acct.saveBank':        'Save Bank Account',
      'acct.saveCard':        'Save Credit Card',
      'acct.cardName':        'Card Name',
      'acct.cardLimit':       'Credit Limit',
      'acct.accounts':        'accounts',

      // Transfers
      'trans.paycheckArrived': 'Paycheck Arrived',
      'trans.payCards':        'Pay Cards',
      'trans.moveMoney':       'Move Money',
      'trans.fundVault':       'Fund Vault',
      'trans.withdraw':        'Withdraw from Vault',
      'trans.execute':         'Execute',
      'trans.available':       'Available',
      'trans.netPay':          'Net Pay',
      'trans.payAmount':       'Pay Amount',
      'trans.from':            'From',
      'trans.to':              'To',
      'trans.allCards':        'Pay All Cards',
      'trans.selectCard':      'Select card',
      'trans.selectVault':     'Select vault',
      'trans.selectBank':      'Select bank account',
      'trans.partial':         'Partial',
      'trans.full':            'Full',

      // Planner
      'plan.paycheckOf':    'of',
      'plan.prevMonth':     'Previous Month',
      'plan.nextMonth':     'Next Month',
      'plan.paycheckAmt':   'Paycheck Amount ($)',
      'plan.category':      'Category',
      'plan.lockAmount':    'Lock',
      'plan.savePaycheck':  'Save Paycheck',
      'plan.customItem':    'Custom Item',
      'plan.customName':    'Name',
      'plan.customAmt':     'Amount',
      'plan.weeklyBudget':  'Weekly Budget Settings',
      'plan.weeklyDesc':    'Food & Gas calculated from day counts',
      'plan.saveWeekly':    'Save Weekly Budgets',
      'plan.perWeek':       '$/wk',
      'plan.upcoming':      'Upcoming Expenses',
      'plan.upcomingDesc':  'planned',
      'plan.addUpcoming':   '+ Add Expense',
      'plan.monthYYYYMM':   'Month (YYYY-MM)',
      'plan.payee':         'Payee / Description',
      'plan.monthTotals':   'Month Totals',
      'plan.notes':         'Notes / Reminders',
      'plan.notesHint':     'e.g. Rent due, car payment, upcoming expense...',
      'plan.reminders':     'Reminders',
      'plan.reminderText':  'Note / Description',
      'plan.reminderDate':  'Due Date',
      'plan.reminderAmt':   'Amount (optional)',
      'plan.addReminder':   '+ Add Reminder',
      'plan.noReminders':   'No reminders yet.',
      'plan.saveReminder':  'Save Reminder',

      // Tracker
      'track.period':        '#',
      'track.payDate':       'Pay Date',
      'track.saved':         'Saved',
      'track.expected':      'Expected',
      'track.variance':      '+/-',
      'track.rank':          'Rank',
      'track.ytdSaved':      'YTD Saved',
      'track.expectedPace':  'Expected Pace',
      'track.aheadOfPace':   'Ahead of Pace',
      'track.behindPace':    'Behind Pace',
      'track.enterHint':     'Enter the amount saved each paycheck -- Tab or Enter to save, ranked automatically.',
      'track.ytdByCategory': 'YTD by Category',
      'track.annualGoal':    'Annual Goal',
      'track.ytdSpent':      'YTD Spent',
      'track.pctOfYear':     '% of Year',
      'track.savingsPlan':   'Savings Plan -- Year-End Projection',
      'track.periodsComplete': 'periods complete',
      'track.remaining':     'remaining',
      'track.projectedTotal':'Projected Total',
      'track.annualGoal2':   'Annual Goal',
      'track.shortfall':     'Shortfall',
      'track.surplusLbl':    'Surplus',
      'track.perCheck':      'Per Check',
      'track.projected':     'Projected',
      'track.challenge':     'Savings Challenge',
      'track.currentAvg':    'Your current avg',
      'track.neededGoals':   'needed for goals',
      'track.matchGoals':    'Match Goals',
      'track.stretch10':     '+10% Stretch',
      'track.ambitious20':   '+20% Ambitious',
      'track.covered':       "you're covered",
      'track.base':          'Base /check',
      'track.plus10':        '+10% /check',
      'track.plus20':        '+20% /check',
      'track.paychecksElapsed': 'paychecks elapsed',
      'track.avg':           'avg',

      // Investments
      'invest.holdings':     'Holdings',
      'invest.ticker':       'Ticker',
      'invest.shares':       'Shares',
      'invest.price':        'Price',
      'invest.value':        'Value',
      'invest.addHolding':   '+ Add Holding',
      'invest.contributions':'Contributions',
      'invest.ytdContrib':   'YTD Contributions',
      'invest.goal':         'Annual Goal',
      'invest.accounts':     'Investment Accounts',
      'invest.totalValue':   'Total Value',
      'invest.rothIra':      'Roth IRA',
      'invest.account':      'Account',

      // Settings / Setup
      'set.account':         'Account',
      'set.theme':           'Theme',
      'set.language':        'Language',
      'set.dark':            'Dark (Neon)',
      'set.light':           'Light',
      'set.system':          'System',
      'set.english':         'English',
      'set.spanish':         'Espanol',
      'set.exportData':      'Export Data',
      'set.importData':      'Import Data',
      'set.clearData':       'Clear All Data',
      'set.income':          'Income',
      'set.categories':      'Savings Categories',
      'set.fixedExpenses':   'Fixed Monthly Expenses',
      'set.frequency':       'Pay Frequency',
      'set.firstPayday':     'First Payday of Year',
      'set.paycheckAmount':  'Default Paycheck Amount',
      'set.addCategory':     '+ Add Category',
      'set.addExpense':      '+ Add Fixed Expense',
      'set.categoryName':    'Category Name',
      'set.annualGoal':      'Annual Goal ($)',
      'set.weeklyBudget':    'Weekly Budget ($)',
      'set.weeklyDay':       'Shopping Day',
      'set.sunday':          'Sunday',
      'set.saturday':        'Saturday',
      'set.targetDate':      'Goal Target Date',
      'set.targetAmount':    'Target Amount ($)',
      'set.saveCategory':    'Save Category',
      'set.saveExpense':     'Save Expense',
      'set.partnerIncome':   'Partner Income',
      'set.partnerEnabled':  'Enable partner income',
    },


      // UI labels — section titles
      'ui.vaults':            'Vaults',
      'ui.bankAccounts':      'Bank Accounts',
      'ui.creditCards':       'Credit Cards',
      'ui.subscriptions':     'Subscriptions',
      'ui.setTarget':         'Set Target',
      'ui.editBalance':       'Edit Balance',
      'ui.addItem':           'Add Item',
      'ui.addPayment':        'Add Payment',
      'ui.saveTarget':        'Save Target',
      'ui.markPaid':          'Mark Paid',
      'ui.addToCheck':        '+ Check',
      'ui.added':             '📋 Added',
      'ui.excludeTransfer':   'Exclude Transfer Acct',
      'ui.transferExcluded':  '✓ Transfer Excluded',
      'ui.noDueDate':         'No fixed date',
      'ui.dueToday':          'Due today',
      // Transfers
      'xfr.paycheckArrived':  'Paycheck Arrived',
      'xfr.payCards':         'Pay Credit Cards',
      'xfr.moveMoney':        'Move Money',
      'xfr.fundVault':        'Fund a Vault',
      'xfr.withdraw':         'Withdraw / Spend',
      'xfr.executePayments':  'Execute Payments',
      'xfr.execute':          'Execute',
      'xfr.payFrom':          'Pay From',
      'xfr.totalPayment':     'Total payment',
      'xfr.accountAfter':     'Account after',
      'xfr.sofiDist':         '↺ SoFi Auto-Distribution',
      // Goals
      'goal.vaultGoals':      'Vault Savings Goals',
      'goal.spendGoals':      'Yearly Spending Goals',
      'goal.noTargets':       'No Savings Targets Set',
      'goal.summary':         '🎯 Savings Goals Summary',
      'goal.totalTarget':     'TOTAL TARGET',
      'goal.savedSoFar':      'SAVED SO FAR',
      'goal.stillNeeded':     'STILL NEEDED',
      'goal.overall':         'overall',
      'goal.noTarget':        'No target set',
      'goal.setFirst':        'Tap the target amount on any vault below to set a savings goal.',
      'goal.withoutTarget':   'vaults without a target',
      // Calendar
      'cal.ytTitle':          'Calendar',
      'cal.addEvent':         'Add Event',
      'cal.eventType':        'Event Type',
      'cal.vacation':         'Vacation',
      'cal.asamblea':         'Assembly',
      'cal.noteType':         'Note',
      'cal.other':            'Other (type it in)',
      'cal.eventName':        'Event Name',
      'cal.notesOpt':         'Notes (optional)',
      'cal.addEventBtn':      'Add Event',
      'cal.otTitle':          '⏱ OT Hours Tracker',
      'cal.period':           'Period',
      'cal.hours':            'Hours',
      'cal.logOT':            '+ Log OT',
      'cal.totalHours':       'TOTAL',
      // Accounts
      'acct.safety':          'Transfer Account Coverage',
      'acct.noTransfer':      'No Transfer Account Set',
      'acct.covered':         '✓ COVERED',
      'acct.short':           '⚠ SHORT',
      'acct.totalCash':       'Total Cash',
      'acct.totalDebt':       'Total Debt',
      'acct.totalVaults':     'Total Vaults',
      'acct.availCredit':     'Available Credit',
      'acct.creditLimit':     'Credit Limit',
      // Entry
      'entry.record':         'Record Transaction',
      'entry.category':       'Category',
      'entry.account':        'Account (optional)',
      'entry.selectCat':      '— Select category —',
      'entry.selectAcct':     '— Select account —',
      'entry.recent':         'Recent Transactions',
      // Tracker
      'track.ytdSummary':     'YTD Summary',
      'track.ytdByCategory':  'YTD by Category',
      'track.annualGoal':     'Annual Goal',
      'track.ytdSpent':       'YTD Spent',
      'track.paceLabel':      'Pace',
      'track.forecast':       '26-Period Year Forecast',
      'track.savPlan':        'Savings Plan — Year-End Projection',
      'track.challenge':      'Savings Challenge',
      // Investments
      'inv.portfolio':        '📊 Portfolio Total',
      'inv.rebalance':        '⚖ Rebalance Calculator',
      'inv.contribLog':       '📋 Contribution Log',
      'inv.addContrib':       '+ Contribution',
      'inv.addHolding':       '+ Add Holding',
      'inv.savePrice':        'Save Prices',
      'inv.ticker':           'Ticker',
      'inv.shares':           'Shares',
      'inv.price':            'Price',
      'inv.targetPct':        'Target %',
      'inv.actualPct':        'Actual %',
      'inv.action':           'Action',
      // Setup
      'setup.categories':     'Spending & Savings Categories',
      'setup.weeklyBudget':   'Weekly Budget',
      'setup.countBy':        'Count by',
      'setup.saturdays':      'Saturdays (Gas)',
      'setup.sundays':        'Sundays (Food)',
      'setup.addCategory':    'Add Category',
      'setup.fixedExpenses':  'Fixed Monthly Expenses',
      'setup.accounts2':      'Accounts & Vaults',
      'setup.income':         'Income Setup',
      'setup.paycheck':       'Paycheck Amount ($)',

      // ── Added missing EN keys ────────────────────────────
      'cal.addEventBtn':    'Add Event',
      'cal.logOT':          'Log OT',
      'common.onTrack':     'On Track',
      'entry.selectAcct':   '— Select Account —',
      'entry.selectCat':    '— Select Category —',
      'goal.spendGoals':    'Spending Goals',
      'goal.vaultGoals':    'Vault Goals',
      'inv.actualPct':      'Actual %',
      'inv.targetPct':      'Target %',
      'plan.saveWeekly':    'Save note',
      'track.aheadOfPace':  'Ahead of pace',
      'track.annualGoal':   'Annual Goal',
      'track.behindPace':   'Behind pace',
      'track.covered':      'Covered',
      'track.matchGoals':   'Match Goals',
      'track.paceLabel':    'Pace',
      'track.ytdSpent':     'YTD Spent',
      'ui.markPaid':        'Mark Paid',
      'xfr.executePayments':'Execute Payments',

      // xfr field labels
      'xfr.payPeriod':        'Pay Period',
      'xfr.amtReceived':      'Amount Received',
      'xfr.dateDeposited':    'Date Deposited',
      'xfr.depositTo':        'Deposit To',
      'xfr.paymentAmount':    'Payment Amount',
      'xfr.extraAdj':         'Extra / Adjustment ($)',
      'xfr.fromBank':         'From (Bank Account)',
      'xfr.vault':            'Vault',
      'xfr.pullFrom':         'Pull From',
      'xfr.recordWithdrawal': 'Record Withdrawal',
      'xfr.noteOpt':          'Note (optional)',
      'xfr.withdrawCash':     'Withdraw / Spend Cash',

    es: {

      // UI Labels
      'ui.vaults':            'Bóvedas',
      'ui.bankAccounts':      'Cuentas Bancarias',
      'ui.creditCards':       'Tarjetas de Crédito',
      'ui.subscriptions':     'Suscripciones',
      'ui.setTarget':         'Establecer Meta',
      'ui.editBalance':       'Editar Saldo',
      'ui.addItem':           'Agregar Ítem',
      'ui.addPayment':        'Agregar Pago',
      'ui.saveTarget':        'Guardar Meta',
      'ui.markPaid':          'Marcar Pagado',
      'ui.addToCheck':        '+ Nómina',
      'ui.added':             '📋 Agregado',
      'ui.excludeTransfer':   'Excluir Cta. Transferencia',
      'ui.transferExcluded':  '✓ Transferencia Excluida',
      'ui.noDueDate':         'Sin fecha fija',
      'ui.dueToday':          'Vence hoy',

      // Navegacion
      'nav.dashboard':   'Tablero',
      'nav.accounts':    'Cuentas',
      'nav.transfers':   'Transferencias',
      'nav.planner':     'Planificador',
      'nav.invest':      'Invertir',
      'nav.settings':    'Ajustes',
      'nav.tracker':     'Registro',
      'nav.entry':       'Entrada',
      'nav.goals':       'Metas',
      'nav.calendar':    'Calendario',
      'nav.paycheck-tracker': 'Reg. Pagos',
      'nav.savings-plan':     'Plan Ahorro',
      'nav.next-year':        'Prox. Año',

      // Paycheck Tracker
      'pct.title':       'Registro de Pagos',
      'pct.addCol':      'Agregar Columna',
      'pct.colName':     'Nombre de columna',
      'pct.removeCol':   'Eliminar columna',
      'pct.period':      'Periodo',
      'pct.total':       'Total',
      'pct.totals':      'Totales',
      'pct.cols':        'Columnas',
      'pct.grandTotal':  'Total General',
      'pct.pace':        'Ritmo',

      // Savings Plan
      'splan.week52':         'Desafío de Ahorro 52 Semanas',
      'splan.biweekly26':     'Desafío de Ahorro 26 Periodos',
      'splan.startAt':        'Empezar en $',
      'splan.week':           'Semana',
      'splan.period':         'Periodo',
      'splan.saveThisWeek':   'Ahorrar Esta Semana',
      'splan.saveThisPeriod': 'Ahorrar Este Periodo',
      'splan.totalSaved':     'Total Ahorrado',
      'splan.yearEnd':        'Total Fin de Año',
      'splan.completed':      'completados',
      'splan.saved':          'ahorrado hasta ahora',

      // Next Year Planner
      'nyp.title':            'Planificador',
      'nyp.resetFromCurrent': 'Resetear del Año Actual',
      'nyp.paycheckAmt':      'Monto del Cheque ($)',
      'nyp.allocated':        'Asignado',
      'nyp.surplus':          'Sobrante',
      'nyp.paychecks':        'Cheques',
      'nyp.lineItems':        'Partidas — Por Cheque',
      'nyp.category':         'Categoría',
      'nyp.perCheck':         '/ Cheque',
      'nyp.annual':           'Anual',
      'nyp.newLineName':      'Nueva partida',
      'nyp.nameRequired':     'El nombre es requerido',
      'nyp.resetDone':        'Categorías del año actual cargadas',
      'nyp.annualSummary':    'Resumen Anual',
      'nyp.totalIncome':      'Ingreso Total',
      'nyp.totalAllocated':   'Total Asignado',
      'nyp.totalSurplus':     'Sobrante Total',
      'nyp.activate':          'Activar para',
      'nyp.activateConfirm':   'Esto actualizará las categorías del año actual con los montos de este plan.',
      'nyp.activateStep1':     'Actualiza el presupuesto semanal en categorías coincidentes',
      'nyp.activateStep2':     'El Planificador usará estos nuevos montos de inmediato',
      'nyp.activateStep3':     'Avanza este planificador a',
      'nyp.activateConfirmBtn':'Activar Ahora',
      'nyp.activateDone':      '¡Activado! Planificador avanzado a',

      // Common
      'cancel':  'Cancelar',
      'add':     'Agregar',

      // Comun
      'common.save':       'Guardar',
      'common.add':        'Agregar',
      'common.edit':       'Editar',
      'common.delete':     'Eliminar',
      'common.cancel':     'Cancelar',
      'common.close':      'Cerrar',
      'common.apply':      'Aplicar',
      'common.lock':       'Bloquear',
      'common.unlock':     'Desbloquear',
      'common.amount':     'Cantidad ($)',
      'common.name':       'Nombre',
      'common.date':       'Fecha',
      'common.note':       'Nota',
      'common.notes':      'Notas',
      'common.total':      'Total',
      'common.balance':    'Saldo',
      'common.goal':       'Meta',
      'common.annual':     'Anual',
      'common.monthly':    'Mensual',
      'common.remaining':  'Restante',
      'common.allocated':  'Asignado',
      'common.surplus':    'Sobrante',
      'common.deficit':    'Deficit',
      'common.fixed':      'fijo',
      'common.custom':     'personalizado',
      'common.perCheck':   '/cheque',
      'common.perYear':    '/ano',
      'common.onTrack':    'Al dia',
      'common.yes':        'Si',
      'common.no':         'No',
      'common.of':         'de',
      'common.paychecks':  'cheques',
      'common.weeks':      'semanas',
      'common.optional':   '(opcional)',
      'common.overridden': 'modificado',

      // Tablero
      'dash.netWorth':        'Patrimonio Neto',
      'dash.safeToSpend':     'Disponible para Gastar',
      'dash.cashOnHand':      'Efectivo disponible',
      'dash.upcomingBills':   'Facturas proximas',
      'dash.allocatedVaults': 'Asignado a fondos',
      'dash.discretionary':   'Discrecional',
      'dash.thisMonth':       'Este Mes',
      'dash.income':          'Ingresos',
      'dash.spent':           'Gastado',
      'dash.netSavings':      'Ahorro Neto',
      'dash.vsLastMonth':     'vs Mes Anterior',
      'dash.savingsGoals':    'Metas de Ahorro',
      'dash.upcomingChanges': 'Cambios Proximos',
      'dash.weeklySpend':     'Control Semanal',
      'dash.weeklyPace':      'Presupuesto semanal vs. gasto real del mes',
      'dash.liquid':          'Liquido (corriente)',
      'dash.available':       'Disponible (ahorros)',
      'dash.invested':        'Invertido',
      'dash.lessDebt':        'Menos: deuda tarjetas',
      'dash.cardAlerts':      'Alertas de Tarjetas',
      'dash.mtdSpent':        'Gastado (mes)',
      'dash.leftThisMonth':   'Disponible (mes)',
      'dash.reminders':       'Recordatorios y Alertas',
      'dash.reminderDue':     'Vence',
      'dash.reminderOverdue': 'Vencido',
      'dash.noReminders':     'Sin recordatorios proximos.',
      'dash.charts':          'Graficas',
      'dash.nwHistory':       'Patrimonio -- 12 Meses',
      'dash.spendingBycat':   'Gasto Mensual por Categoria',
      'dash.investGrowth':    'Crecimiento de Inversiones',
      'dash.paycheckPerf':    'Rendimiento por Cheque',

      // Cuentas
      'acct.vaults':          'Fondos',
      'acct.bankAccounts':    'Cuentas Bancarias',
      'acct.creditCards':     'Tarjetas de Credito',
      'acct.totalVaults':     'Total Fondos',
      'acct.totalCash':       'efectivo total',
      'acct.totalDebt':       'Deuda Total',
      'acct.safetyNet':       'Fondo de Emergencia',
      'acct.safetyNetDesc':   'meses de gastos cubiertos',
      'acct.addVault':        '+ Agregar Fondo',
      'acct.addBank':         '+ Agregar Cuenta Bancaria',
      'acct.addCard':         '+ Agregar Tarjeta',
      'acct.limit':           'Limite',
      'acct.used':            'usado',
      'acct.liquid':          'Inmediato',
      'acct.short':           'Corto plazo',
      'acct.locked':          'Bloqueado',
      'acct.isTransfer':      'Cuenta de transferencia',
      'acct.vaultName':       'Nombre del Fondo',
      'acct.linkedCategory':  'Categoria vinculada',
      'acct.liquidityTier':   'Nivel de Liquidez',
      'acct.editVault':       'Editar Fondo',
      'acct.editBank':        'Editar Cuenta Bancaria',
      'acct.editCard':        'Editar Tarjeta',
      'acct.saveVault':       'Guardar Fondo',
      'acct.saveBank':        'Guardar Cuenta Bancaria',
      'acct.saveCard':        'Guardar Tarjeta',
      'acct.cardName':        'Nombre de la Tarjeta',
      'acct.cardLimit':       'Limite de Credito',
      'acct.accounts':        'cuentas',

      // Transferencias
      'trans.paycheckArrived': 'Llego el Cheque',
      'trans.payCards':        'Pagar Tarjetas',
      'trans.moveMoney':       'Mover Dinero',
      'trans.fundVault':       'Depositar en Fondo',
      'trans.withdraw':        'Retirar del Fondo',
      'trans.execute':         'Ejecutar',
      'trans.available':       'Disponible',
      'trans.netPay':          'Pago Neto',
      'trans.payAmount':       'Monto a Pagar',
      'trans.from':            'De',
      'trans.to':              'A',
      'trans.allCards':        'Pagar Todas las Tarjetas',
      'trans.selectCard':      'Seleccionar tarjeta',
      'trans.selectVault':     'Seleccionar fondo',
      'trans.selectBank':      'Seleccionar cuenta bancaria',
      'trans.partial':         'Parcial',
      'trans.full':            'Completo',

      // Planificador
      'plan.paycheckOf':    'de',
      'plan.prevMonth':     'Mes Anterior',
      'plan.nextMonth':     'Mes Siguiente',
      'plan.paycheckAmt':   'Monto del Cheque ($)',
      'plan.category':      'Categoria',
      'plan.lockAmount':    'Fijar',
      'plan.savePaycheck':  'Guardar Cheque',
      'plan.customItem':    'Elemento Personalizado',
      'plan.customName':    'Nombre',
      'plan.customAmt':     'Cantidad',
      'plan.weeklyBudget':  'Presupuesto Semanal',
      'plan.weeklyDesc':    'Comida y Gasolina calculados por dias del mes',
      'plan.saveWeekly':    'Guardar Presupuesto Semanal',
      'plan.perWeek':       '$/sem',
      'plan.upcoming':      'Gastos Proximos',
      'plan.upcomingDesc':  'planificados',
      'plan.addUpcoming':   '+ Agregar Gasto',
      'plan.monthYYYYMM':   'Mes (AAAA-MM)',
      'plan.payee':         'Beneficiario / Descripcion',
      'plan.monthTotals':   'Totales del Mes',
      'plan.notes':         'Notas / Recordatorios',
      'plan.notesHint':     'Ej. Renta vence, pago de auto, gasto proximo...',
      'plan.reminders':     'Recordatorios',
      'plan.reminderText':  'Nota / Descripcion',
      'plan.reminderDate':  'Fecha de Vencimiento',
      'plan.reminderAmt':   'Cantidad (opcional)',
      'plan.addReminder':   '+ Agregar Recordatorio',
      'plan.noReminders':   'Sin recordatorios aun.',
      'plan.saveReminder':  'Guardar Recordatorio',

      // Registro
      'track.period':        '#',
      'track.payDate':       'Fecha de Pago',
      'track.saved':         'Ahorrado',
      'track.expected':      'Esperado',
      'track.variance':      '+/-',
      'track.rank':          'Posicion',
      'track.ytdSaved':      'Ahorrado (YTD)',
      'track.expectedPace':  'Ritmo Esperado',
      'track.aheadOfPace':   'Adelante',
      'track.behindPace':    'Atrasado',
      'track.enterHint':     'Ingresa el monto ahorrado por cheque -- Tab o Enter para guardar.',
      'track.ytdByCategory': 'YTD por Categoria',
      'track.annualGoal':    'Meta Anual',
      'track.ytdSpent':      'Gastado (YTD)',
      'track.pctOfYear':     '% del Ano',
      'track.savingsPlan':   'Plan de Ahorro -- Proyeccion Anual',
      'track.periodsComplete': 'periodos completos',
      'track.remaining':     'restantes',
      'track.projectedTotal':'Total Proyectado',
      'track.annualGoal2':   'Meta Anual',
      'track.shortfall':     'Deficit',
      'track.surplusLbl':    'Sobrante',
      'track.perCheck':      'Por Cheque',
      'track.projected':     'Proyectado',
      'track.challenge':     'Desafio de Ahorro',
      'track.currentAvg':    'Tu promedio actual',
      'track.neededGoals':   'necesario para metas',
      'track.matchGoals':    'Cumplir Metas',
      'track.stretch10':     '+10% Esfuerzo',
      'track.ambitious20':   '+20% Ambicioso',
      'track.covered':       'ya lo alcanzas',
      'track.base':          'Base /cheque',
      'track.plus10':        '+10% /cheque',
      'track.plus20':        '+20% /cheque',
      'track.paychecksElapsed': 'cheques transcurridos',
      'track.avg':           'prom',

      // Inversiones
      'invest.holdings':     'Posiciones',
      'invest.ticker':       'Simbolo',
      'invest.shares':       'Acciones',
      'invest.price':        'Precio',
      'invest.value':        'Valor',
      'invest.addHolding':   '+ Agregar Posicion',
      'invest.contributions':'Contribuciones',
      'invest.ytdContrib':   'Contribuciones YTD',
      'invest.goal':         'Meta Anual',
      'invest.accounts':     'Cuentas de Inversion',
      'invest.totalValue':   'Valor Total',
      'invest.rothIra':      'Roth IRA',
      'invest.account':      'Cuenta',

      // Ajustes
      'set.account':         'Cuenta',
      'set.theme':           'Tema',
      'set.language':        'Idioma',
      'set.dark':            'Oscuro (Neon)',
      'set.light':           'Claro',
      'set.system':          'Sistema',
      'set.english':         'English',
      'set.spanish':         'Espanol',
      'set.exportData':      'Exportar Datos',
      'set.importData':      'Importar Datos',
      'set.clearData':       'Borrar Todos los Datos',
      'set.income':          'Ingresos',
      'set.categories':      'Categorias de Ahorro',
      'set.fixedExpenses':   'Gastos Fijos Mensuales',
      'set.frequency':       'Frecuencia de Pago',
      'set.firstPayday':     'Primer Dia de Pago del Ano',
      'set.paycheckAmount':  'Monto Predeterminado del Cheque',
      'set.addCategory':     '+ Agregar Categoria',
      'set.addExpense':      '+ Agregar Gasto Fijo',
      'set.categoryName':    'Nombre de la Categoria',
      'set.annualGoal':      'Meta Anual ($)',
      'set.weeklyBudget':    'Presupuesto Semanal ($)',
      'set.weeklyDay':       'Dia de Compras',
      'set.sunday':          'Domingo',
      'set.saturday':        'Sabado',
      'set.targetDate':      'Fecha Meta',
      'set.targetAmount':    'Cantidad Meta ($)',
      'set.saveCategory':    'Guardar Categoria',
      'set.saveExpense':     'Guardar Gasto',
      'set.partnerIncome':   'Ingresos del Conyuge',
      'set.partnerEnabled':  'Activar ingresos del conyuge',
      // Additional keys
      'cal.addEventBtn': 'Agregar Evento',
      'cal.logOT': 'Registrar HE',
      'entry.category': 'Categoría',
      'entry.recent': 'Transacciones Recientes',
      'entry.record': 'Registrar',
      'entry.selectAcct': '-- Seleccionar Cuenta --',
      'entry.selectCat': '-- Seleccionar Categoría --',
      'goal.spendGoals': 'Metas de Gastos',
      'goal.vaultGoals': 'Metas de Bóvedas',
      'inv.actualPct': '% Real',
      'inv.rebalance': 'Rebalancear',
      'inv.shares': 'Acciones',
      'inv.targetPct': '% Meta',
      'inv.ticker': 'Símbolo',
      'track.paceLabel': 'Ritmo',
      'xfr.executePayments': 'Ejecutar Pagos',
      'xfr.payCards': 'Pagar Tarjetas',
      // ── Added missing ES keys ────────────────────────────
      'acct.covered':       'Cubierto',
      'acct.safety':        'Fondo de emergencia',
      'cal.asamblea':       'Asamblea',
      'cal.hours':          'Horas',
      'cal.other':          'Otro',
      'cal.period':         'Periodo',
      'cal.vacation':       'Vacaciones',
      'common.onTrack':     'Al día',
      'entry.account':      'Cuenta',
      'goal.overall':       'General',
      'goal.summary':       'Resumen',
      'inv.action':         'Acción',
      'inv.portfolio':      'Portafolio',
      'inv.price':          'Precio',
      'plan.saveWeekly':    'Guardar nota',
      'setup.accounts2':    'Cuentas',
      'setup.categories':   'Categorías',
      'setup.income':       'Ingresos',
      'setup.paycheck':     'Nómina',
      'setup.saturdays':    'Sábados',
      'setup.sundays':      'Domingos',
      'track.aheadOfPace':  'Por delante',
      'track.annualGoal':   'Meta Anual',
      'track.behindPace':   'Por detrás',
      'track.covered':      'Cubierto',
      'track.forecast':     'Proyección',
      'track.matchGoals':   'Igualar metas',
      'track.ytdSpent':     'Gastado YTD',
      'ui.markPaid':        'Marcar Pagado',
      'xfr.execute':        'Ejecutar',
      'xfr.executePayments':'Ejecutar Pagos',
      'xfr.withdraw':       'Retirar',

      // xfr keys — ES
      'xfr.paycheckArrived':  'Llegó el Cheque',
      'xfr.moveMoney':        'Mover Dinero',
      'xfr.fundVault':        'Depositar en Bóveda',
      'xfr.payFrom':          'Pagar Desde',
      'xfr.totalPayment':     'Total a Pagar',
      'xfr.accountAfter':     'Cuenta después',
      'xfr.sofiDist':         '↺ Auto-Distribución SoFi',
      'xfr.payPeriod':        'Periodo de Pago',
      'xfr.amtReceived':      'Cantidad Recibida',
      'xfr.dateDeposited':    'Fecha de Depósito',
      'xfr.depositTo':        'Depositar En',
      'xfr.paymentAmount':    'Monto de Pago',
      'xfr.extraAdj':         'Extra / Ajuste ($)',
      'xfr.fromBank':         'De (Cuenta Bancaria)',
      'xfr.vault':            'Bóveda',
      'xfr.pullFrom':         'Retirar De',
      'xfr.recordWithdrawal': 'Registrar Retiro',
      'xfr.noteOpt':          'Nota (opcional)',
      'xfr.withdrawCash':     'Retirar / Gastar Efectivo',

    }
  
    };

  var _lang = 'en';


  function updateToggleBtn() {
    var btn = document.getElementById('lang-toggle');
    if (btn) btn.textContent = '🌐 ' + (_lang === 'es' ? 'ES' : 'EN');
  }

  function t(key) {
    var dict = STRINGS[_lang] || STRINGS['en'];
    return dict[key] !== undefined ? dict[key] : (STRINGS['en'][key] || key);
  }

  function setLang(lang) {
    if (lang !== 'en' && lang !== 'es') return;
    _lang = lang;
    // Persist
    try {
      var state = App.Storage ? App.Storage.loadState() : null;
      if (state) {
        if (!state.settings) state.settings = {};
        state.settings.lang = lang;
        App.Storage.saveState(state);
      }
      localStorage.setItem('financeApp_lang', lang);
    } catch(e) {}
    // Re-render current tab
    if (App.refreshCurrentTab) App.refreshCurrentTab();
    updateToggleBtn();
    // Update nav labels
    updateNavLabels();
    // Update html lang attribute
    document.documentElement.lang = lang;
  }

  function getLang() { return _lang; }

  function init() {
    // Load saved lang
    try {
      var saved = localStorage.getItem('financeApp_lang');
      if (saved === 'en' || saved === 'es') _lang = saved;
      updateToggleBtn();
    } catch(e) {}
    updateNavLabels();
    document.documentElement.lang = _lang;
  }

  function updateNavLabels() {
    var map = {
      'dashboard':   'nav.dashboard',
      'accounts':    'nav.accounts',
      'transfers':   'nav.transfers',
      'planner':     'nav.planner',
      'investments': 'nav.invest',
      'settings':    'nav.settings',
      'goals':       'nav.goals',
      'calendar':    'nav.calendar',
      'paycheck-tracker': 'nav.paycheck-tracker',
      'savings-plan':     'nav.savings-plan',
      'next-year':        'nav.next-year'
    };
    document.querySelectorAll('.tab-btn[data-tab]').forEach(function(btn) {
      var key = map[btn.dataset.tab];
      if (key) {
        var label = btn.querySelector('.tab-label');
        if (label) label.textContent = t(key);
      }
    });
    // Also update the lang toggle button text if it exists
    // Two-button lang selector
    var enBtn = document.getElementById('lang-en');
    var esBtn = document.getElementById('lang-es');
    if (enBtn && esBtn) {
      enBtn.classList.toggle('active', _lang === 'en');
      esBtn.classList.toggle('active', _lang === 'es');
    }
  }

  App.Lang = { t: t, setLang: setLang, getLang: getLang, init: init };

})(window.App = window.App || {});
